#!/bin/bash

# header
curl -sO "https://raw.githubusercontent.com/jejusee/script/main/linux/_common"; source "_common";  # 필수

#
function initialize() {
}

#
function install_docker() {
}

#
function install_rclone() {
}

#
while :; do
  clear

  output_title "리눅스 세팅 스크립트($OS_CMD)" "[$HOSTNAME] $OS_NAME $OS_VERSION($ARCHITECTURE)"

  echo ""
  echo " 1) update"
  echo " 2) docker & docker-compose 설치"
  echo " 3) rclone 설치 (이치로님 버전)"
  echo ""
  echo " q) 종료"
  echo ""
  echo "$LINE"

read -p "# 원하시는 기능을 입력하세요.> " SELECT_VALUE
  echo ""

  case $SELECT_VALUE in
    1) update_os;;
    2) install_docker;;
    3) install_rclone;;
    q) break;;
  esac

  read -p "# 계속하려면 아무키나 누르세요..."
done
