#!/bin/bash

# header
curl -sO "https://raw.githubusercontent.com/jejusee/script/main/linux/_common"; source "_common";  # 필수

#
function update_os() {
  case $OS_CMD in
    apt) sudo apt update -y && sudo apt upgrade -y;;
    yum) sudo yum update -y && sudo yum upgrade -y;;
    dnf) sudo dnf update -y && sudo dnf upgrade -y;;
    *) return;;
  esac
  read -p "# 계속하려면 아무키나 누르세요..."
}
#
function install_docker() {
  case $OS_CMD in
    apt) ;;
    yum) ;;
    dnf) ;;
    *) return;;
  esac
  read -p "# 계속하려면 아무키나 누르세요..."
}

#
while :; do
  clear

  output_title "리눅스 세팅 스크립트($OS_CMD)" "[$HOSTNAME] $OS_NAME $OS_VERSION($ARCHITECTURE)"

  echo ""
  echo " 1) update"
  echo " 2) docker & docker-compose 설치"
  echo ""
  echo " q) 종료"
  echo ""
  
  output_line

  read -p "# 원하시는 기능을 입력하세요.> " SELECT_VALUE
  echo ""

  case $SELECT_VALUE in
    1) update_os;;
    2) install_docker;;
    quit) break;;
  esac

done
